/* features */
#include <unistd.h>

/* constants used in APIs */

int ic[] = {
  _CS_POSIX_V6_ILP32_OFF32_CFLAGS,
  _CS_POSIX_V6_ILP32_OFF32_LDFLAGS,
  _CS_POSIX_V6_ILP32_OFF32_LIBS,
  _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS,
  _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS,
  _CS_POSIX_V6_ILP32_OFFBIG_LIBS,
  _CS_POSIX_V6_LP64_OFF64_CFLAGS,
  _CS_POSIX_V6_LP64_OFF64_LDFLAGS,
  _CS_POSIX_V6_LP64_OFF64_LIBS,
  _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS,
  _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS,
  _CS_POSIX_V6_LPBIG_OFFBIG_LIBS,
  _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS,
  _CS_V6_ENV,

  _PC_2_SYMLINKS,
  _PC_ALLOC_SIZE_MIN,
  _PC_REC_INCR_XFER_SIZE,
  _PC_REC_MIN_XFER_SIZE,
  _PC_REC_XFER_ALIGN,
  _PC_SYMLINK_MAX,

  _SC_2_CHAR_TERM,
  _SC_2_PBS,
  _SC_2_PBS_ACCOUNTING,
  _SC_2_PBS_CHECKPOINT,
  _SC_2_PBS_LOCATE,
  _SC_2_PBS_MESSAGE,
  _SC_2_PBS_TRACK,
  _SC_ADVISORY_INFO,
  _SC_BARRIERS,
  _SC_CLOCK_SELECTION,
  _SC_CPUTIME,
  _SC_HOST_NAME_MAX,
  _SC_IPV6,
  _SC_MONOTONIC_CLOCK,
  _SC_RAW_SOCKETS,
  _SC_READER_WRITER_LOCKS,
  _SC_REGEXP,
  _SC_SHELL,
  _SC_SPAWN,
  _SC_SPIN_LOCKS,
  _SC_SPORADIC_SERVER,
  _SC_SS_REPL_MAX,
  _SC_SYMLOOP_MAX,
  _SC_THREAD_CPUTIME,
  _SC_THREAD_SPORADIC_SERVER,
  _SC_TIMEOUTS,
  _SC_TRACE,
  _SC_TRACE_EVENT_FILTER,
  _SC_TRACE_EVENT_NAME_MAX,
  _SC_TRACE_INHERIT,
  _SC_TRACE_LOG,
  _SC_TRACE_NAME_MAX,
  _SC_TRACE_SYS_MAX,
  _SC_TRACE_USER_EVENT_MAX,
  _SC_TYPED_MEMORY_OBJECTS,
  _SC_V6_ILP32_OFF32,
  _SC_V6_ILP32_OFFBIG,
  _SC_V6_LP64_OFF64,
  _SC_V6_LPBIG_OFFBIG,
  _SC_XOPEN_STREAMS,
};

void f(void)
{
  int (*a)(char *, size_t) = gethostname;
  int (*b)(gid_t) = setegid;
  int (*c)(uid_t) = seteuid;
}
